In [59]:
res = []
with open("Symphony_No._5_1st_Movement_chordroman124.txt") as f:
    for line in f:
        line = line.rstrip()
        s = line.split(" | ")
        measure, beat = s[0][1:-1].split(", ")
        vector = []
        for i in s[1][1:-1].split(", "):
            vector.append(int(i))
        ck = s[2].split(",")
        if len(ck)==2:
            chord, key = ck[0], ck[1]
            lchord, lkey = ck[0], ck[1]
        else:
            chord, key = lchord, lkey
        res.append({"measure": measure, "beat":beat, "vector":vector, "chord":chord, "key":key})
f.close()

In [60]:
print(res)

[{'measure': '1', 'beat': '1.0', 'vector': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '2', 'beat': '1.0', 'vector': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '3', 'beat': '1.0', 'vector': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '4', 'beat': '1.0', 'vector': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '5', 'beat': '1.0', 'vector': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '6', 'beat': '1.0', 'vector': [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], 'chord': 'N/A', 'key': 'CMinor'}, {'measure': '7', 'beat': '1.0', 'vector': [1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0], 'chord': 'I', 'key': 'CMinor'}, {'measure': '8', 'beat': '1.0', 'vector': [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0], 'chord': 'I', 'key': 'CMinor'}, {'measure': '9', 'beat': '1.0', 'vector': [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0], 'chord': 'I

In [61]:
keylist = []
for i in res:
    if i['key'] not in keylist:
        print(i['key'])
        keylist.append(i['key'])

CMinor
B-Major
E-Major
FMinor
A-Major


In [62]:
CMinor = []
BbMajor = []
EbMajor = []
FMinor = []
AbMajor = []

FMajor = []
CMajor = []
GMajor = []
DMinor = []
GMinor = []
EMajor = []
DMajor = []

AMinor = []


chords = ['I', 'I+', 'IIb', 'II', 'II7', 'III', 'IV', 'V', 'V7', 'V+', 'V+7', 'VIb', 'VI','VI7','VIGer', 'VII', 'VII7', 'VIIGer', 'VIIIta', 'VIIdim', 'VIIdim7']
tran = {
    'I':0, 
    'I+':1, 
    'IIb':2, 
    'II':3, 
    'II7':4, 
    'III':5, 
    'IV':6, 
    'V':7, 
    'V7':8, 
    'V+':9, 
    'V+7':10, 
    'VIb':11, 
    'VI':12, 
    'VI7':13,
    'VIGer':14, 
    'VII':15, 
    'VII7':16, 
    'VIIGer':17, 
    'VIIIta':18, 
    'VIIdim':19, 
    'VIIdim7':20
}

In [5]:
import numpy as np

In [45]:
a = np.zeros((21,21))

In [38]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.,

In [63]:
a = np.zeros((21,21))
lkey = 'N/A'
lchord = 'N/A'
for i in res:
    if lkey=='B-Major' and i['key']=='B-Major' and lchord!='N/A' and i['chord']!='N/A':
        row = tran[lchord]
        col = tran[i['chord']]
        a[row][col] = a[row][col] + 1
    lkey = i['key']
    lchord = i['chord']

In [64]:
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0.

In [16]:
import matplotlib as mpl

In [17]:
from matplotlib import pyplot

In [41]:
fig = pyplot.figure(2)
cmap2 = mpl.colors.LinearSegmentedColormap.from_list('my_colormap',
                                           ['white','grey','black'],
                                           256)

img2 = pyplot.imshow(a,interpolation='nearest',
                    cmap = cmap2,
                    origin='lower')

fig.savefig("image5.png")

In [1]:
import pickle

def load_obj(name):
    with open("Scores/" + name + '.pkl', 'rb') as f:
        return pickle.load(f)
    
a = load_obj("W.A.Mozart_-_Symphony_No._25_The_Little_G_minor_Symphony_-_1st_movement_chordroman")
b = load_obj("Symphony_No._1_1st_Movement_chordroman111")
c = load_obj("Symphony_No._5_1st_Movement_chordroman124")
chord_dict = {}
for i in a+b+c:
    if i[1] not in chord_dict:
        chord_dict.update({i[1]:1})
    else:
        chord_dict[i[1]] += 1
print(chord_dict)

{'I': 239, 'V+7': 40, 'II': 37, 'V+': 23, 'IV': 34, 'IIb': 1, 'VIIIta': 1, 'V7': 68, 'VII': 15, 'III': 8, 'VI': 14, 'VIIdim7': 33, 'VIIdim': 7, 'I+': 10, 'V': 29, 'VIb': 9, 'VIIGer': 3, 'II7': 7, 'VI7': 1, 'VIGer': 1, 'VII7': 2}


In [4]:
d = load_obj("Oboe Concerto K314")
print(d)

[[1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1], [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], [0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0], [1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1], [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0], [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1], [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0], [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1], [1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1], [1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1], [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1], [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0], [1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1], [1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1], [1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0], [1, 0, 0, 0